# Build Stage
FROM node:20-alpine AS builder

# Add build arguments for Firebase (required for Next.js static build)
ARG NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyACk7G1pClIIVXgMwzGI8othZVexL58hHU
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=legal12-kontakt.firebaseapp.com
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID=legal12-kontakt
ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=legal12-kontakt.firebasestorage.app
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=895536839180
ARG NEXT_PUBLIC_FIREBASE_APP_ID=1:895536839180:web:d5636f343eb79f5d81cc29
ARG NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=G-731BZ2G3SLq

# Set build arguments as ENV for the build process
ENV NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ENV NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID
ENV NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=$NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
ENV NODE_ENV=production

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json* ./
RUN npm ci --include=dev

# Copy source and build
COPY . .
RUN npm run build

# Final Stage: Node.js server
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=8080
ENV HOSTNAME="0.0.0.0"

# Set runtime environment variables for Firebase
ENV NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyACk7G1pClIIVXgMwzGI8othZVexL58hHU
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=legal12-kontakt.firebaseapp.com
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=legal12-kontakt
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=legal12-kontakt.firebasestorage.app
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=895536839180
ENV NEXT_PUBLIC_FIREBASE_APP_ID=1:895536839180:web:d5636f343eb79f5d81cc29
ENV NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=G-731BZ2G3SLq

COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public
COPY --from=builder /app/scripts ./scripts

EXPOSE 8080
CMD ["node", "server.js"]
